### ISSUE TITLE
How to go directly to a path, e.g. for putting a reset token

### ISSUE THREAD

**Issue by Daryn-L** [kitze/mobx-router#103]
Hi guys,

I am trying to integrate a reset password token that gets emailed to the user.  Is it possible to integrate this into mobx-router?  e.g. they get emailed a link with a uuid.  www.mywebsite.com/reset-password/565456-465-645654-465645

e.g. Something like:

```
 resetPassword: new Route<RootStore, { 
    token?: string 
  }>({
    path: '/reset-password/:token',
    component: <ResetPassword />,
    beforeEnter: (route, params, store) => {
      console.log(params.token)     
     
    },
  }),
```
However it just redirects to the /reset-password page and the token is null
quite new to all this...

Any help would be appreciated

**Comment by Daryn-L** [comment]
As a workaround I have managed to do the following:

In my main App.tsx

```
React.useEffect(() => {
        // extracting url query params
        console.log(window.location)
        const params = new URLSearchParams(window.location.search);
        const token = params.get('reset-password-token');
        if(token){
            store.app.resetToken=token
            store.router.goTo(routes.resetPassword)
        }      
      },
      []);
```

Then if I go to www.mywebsite.com?reset-password-token=23432-234-234324-234324

The token will be in the store

Not sure if this is a good solution or not...

**Comment by thdk** [comment]
Should be fixed when #102 is merged.

I'll try to look at merging it asap. Meanwhile you could try version 0.2.10

**Comment by Daryn-L** [comment]
Thanks for that.
Can confirm v0.2.9 works correctly but not any later.
Cheers!

**Comment by thdk** [comment]
@Daryn-L released new version with fix for your issue.
