### ISSUE TITLE
Having issue with director.Route.init()

### ISSUE THREAD

**Issue by aap82** [kitze/mobx-router#11]
Submitted pull request for simple fix.  See [this](https://github.com/flatiron/director/issues/332)

Question to follow.

**Comment by kitze** [comment]
@aap82 thanks for the fix, just merged the PR and released 0.0.7 with it

**Comment by aap82** [comment]
@kitze np.  took me longer than usual to figure out....i may or may not have completely deleted the repository from my project because of this. :)
