### ISSUE TITLE
null || '' ??

### ISSUE THREAD

**Issue by romazhan** [kitze/mobx-router#119]
https://github.com/kitze/mobx-router/blob/d8b65c6b7253b233d3e4ef01c7c6535e1d45339d/src/start-router.ts#L44

**Comment by thdk** [comment]
@polak228 Can you give some more info on this issue? Are you experiencing problems with this line?

**Comment by romazhan** [comment]
Why write null || "?

**Comment by thdk** [comment]
Ah that's indeed a bit silly 🙂

So it's always `''`

Is there a better value than empty string for this argument?

**Comment by romazhan** [comment]
Write just '', it will work faster by 0.0001 seconds

**Comment by thdk** [comment]
Yes, according to the docs https://developer.mozilla.org/en-US/docs/Web/API/History/pushState it should be empty string as this value is never used and exists only for historical reasons.

Feel free to submit a PR. 

Still not sure how you stumbled on this line though but that's none of my business :)

**Comment by romazhan** [comment]
It's just that sometimes I like to dig into someone else's code
