### ISSUE TITLE
PropTypes error

### ISSUE THREAD

**Issue by codyhatch** [kitze/mobx-router#13]
I've added `mobx-router` to a project and started getting a new error:

```
Warning: You are manually calling a React.PropTypes validation function for the
`mobxStores` prop on `MobXStoreInjector`. This is deprecated and will not work
in the next major version. You may be seeing this warning due to a third-party
PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

The key for this seems to be trying to render the `<MobxRouter />` component; the contents of the views, or whether I even call `startRouter` seems to have no impact.

I'm at a bit of a loss as to how to resolve this.

**Comment by aap82** [comment]
See https://github.com/mobxjs/mobx-react/blob/master/CHANGELOG.md#using-observer-to-inject-stores-is-deprecated
