### ISSUE TITLE
Catchall/Not found

### ISSUE THREAD

**Issue by peterbe** [kitze/mobx-router#15]
How should you best implement a notfound route?

**Comment by VolCh** [comment]
Director has 'notfound' in configure options, but mobx-router use only one ('html5history') of them and it hardcoded in createDirectorRouter. I think the simplest way - add options param in createDirectorRouter & startRouter functions and path it to director.configure

**Comment by thdk** [comment]
Exposed the director configuration object as third argument of the `startRouter`method so you can now use the `notfound` callback. I've added an example to the readme.

Released in version 0.3.0
