### ISSUE TITLE
Split into router, react and react-native proposal/discussion

### ISSUE THREAD

**Issue by pietgk** [kitze/mobx-router#2]
Kristijan,
i would like to use mobx-router in a react-native project.

we should agree on how to tackle this.

any suggestions?

--piet

**Comment by kitze** [comment]
Hey @pietgk i already have an idea about this. It's a pretty simple change actually!

**Comment by pietgk** [comment]
Hi @Kitze, let me know if i can help.

**Comment by kitze** [comment]
@pietgk you can already use this with react-native. Just don't call the startRouter function anywhere. The startRouter function is responsible for handling the url and the changes in the url.

**Comment by kitze** [comment]
@pietgk when I think about it, this doesn't make any sense for react-native right now. It will work, but you won't get any "back button" functionality because the views are not pushed into a stack. The old view is just replaced with a new view.

**Comment by pietgk** [comment]
@kitze,

I like the simplicity and separation of mobx-router.
My RN app already needs some logic to handle back in a web view combined with react-native-router-flux.
I will give it a try when the app is in the app stores and i can take the time for refactoring routing.

This afaikt would mean implementing a stack for back button functionality.  

Then I wonder if we/i would need a new repository for a RN version.

**Comment by kitze** [comment]
@pietgk for now i will focus on the web version of mobx-router, you can of course fork it and try to do a reasonable PR that will allow integration with react-native.

Cheers
