### ISSUE TITLE
Style Active Link

### ISSUE THREAD

**Issue by timkendall** [kitze/mobx-router#20]
We should have a way to easily mark a `Link` component as "active" if it is a link for the current viewing (including `params` and `queryParams`).

With styled components I've been experimenting with something like this (note that this approach doesn't yet take into account params or queryParams):

```js
const active = (activeStyle) => ({
  default: (defaultStyle) => (props) => {
    const { router, view } = props
    const isCurrent = router.currentView === view

    return isCurrent ? activeStyle : defaultStyle
  }
})

const StyledLink = styled(Link)`
  width: 70px;
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 250ms ease;
  background: ${
    active('linear-gradient(-42deg, #D264C6 0%, #FB4078 100%)')
    .default('none')
  };
`
```

**Comment by timkendall** [comment]
Wait awkward...can just use the default browser `a:active`.

**Comment by kitze** [comment]
Ah, good idea! I will have some more time to work on the router soon, meanwhile you can submit a PR :)

**Comment by timkendall** [comment]
Planning on it!

**Comment by timkendall** [comment]
Todo:
- [ ] Implementation (implement both `activeStyle` and `activeClassName` like React-Router)
- [ ] Update documentation

**Comment by kitze** [comment]
Is this done @timkendall ?

**Comment by timkendall** [comment]
No it's not. I stopped working on it for now as I've been busy with other things. Still think it's a good thing to have as core functionality though. Perhaps someone else can pick this up?

**Comment by kitze** [comment]
I'm not a fan of async routes *at all* so that's why it's not part of core functionality. I think that the flow of:

1. click a link
2. wait for something to happen (i.e loading data)
3. go to that link

should be handled by the user manually, not the router library.

I stand by this point but I really would like to be proven otherwise :)

**Comment by timkendall** [comment]
I'm not a huge fan of them either, but I'll play devil's advocate.

Async routes seem to generally be used to tie route rendering to a
requirement that some data or async task be completed before the user is
allowed to access the route. Sure we could manually handle this in our
components (i.e show a loading state while the async is happening) but
pushing this to the routing layer gives us a few advantages -

1. Central location and paradigm to handle route loading states (Ember.js
does this)
2. Easier to reason about (i.e I know this route can only be rendered if
this async action succeeds)
3. Easier to test (ex. "Did the URL change when the async action
completed?")

Regardless, I think this issue largely comes down to a matter of preference.

**Comment by elilambnz** [comment]
Alternatively, you could rely on the RouterStore to return a bool depending on the current view.

```javascript
active={this.props.store.router.currentView.path === "/path"}
```
This works well for components like Bootstrap NavLink that have an `active` prop.

For a classname, you could do something like:
```javascript
className={this.props.store.router.currentView.path ? 'activeStyle' : 'defaultStyle'}
```
