### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LeonardoGentile** [kitze/mobx-router#27]
Hello, I've tried to dive into your code and many things do not work as expected or as presented in the docs. I like this project but I guess the doc is not up to date. 
An example is the `router.goTo(views.book)` generates a `view.replaceUrlParams is not a function` because the `goTo` method expect [more parameters](https://github.com/kitze/mobx-router/blob/master/src/router-store.js#L13) to be passed to it.

Another example is how we start the router, see #17.

Is this project maintained, meaning I could invest some time diving into it also to help you somehow or was this just a weekend experiment? 

BTW: director is unmaintained, last commit was done 2 years ago, check this out: https://github.com/CodeYellowBV/tarantino

**Comment by kitze** [comment]
Yeah @LeonardoGentile, I need to update the project docs a little bit. Will be done soon!

**Comment by LeonardoGentile** [comment]
Hi @kitze 
In the end I've taken another ehmm..route and implemented my own version of mobx-router as a plugin of router5, take a look at a very early version: https://github.com/LeonardoGentile/mobx-router5

Maybe we could converge some day ;)

**Comment by kitze** [comment]
Looks nice @LeonardoGentile, good luck! 🙌
