### ISSUE TITLE
Wrapping view in extra div

### ISSUE THREAD

**Issue by jayalfredprufrock** [kitze/mobx-router#30]
While migrating over to mobx-router, I noticed my views are getting wrapped in a `<div>` and causing a layout styling problem. Is this extra div necessary? If so would it be possible to provide at least a prop for adding custom styles to it?

**Comment by jayalfredprufrock** [comment]
I was able to remove the extra div without altering any other behavior by changing the code in MobxRouter.jsx like this:

```
const MobxRouter = ({store:{router}}) => { (router.currentView && router.currentView.component) ? router.currentView.component : <div></div>};
```

**Comment by thdk** [comment]
I would also prefer not to have a wrapping div. 

@kitze do you see any problems with the fix suggested by @jayalfredprufrock ?

**Comment by thdk** [comment]
Oops got a typo.. Fixed in second commit. Still untested, will submit pr when tested.
