### ISSUE TITLE
allow configuration without html5history, aka hash routing

### ISSUE THREAD

**Issue by jayalfredprufrock** [kitze/mobx-router#31]
As of now, mobx-router forces you to use html5history routing w/ pushState, however this isn't always desirable with SPA or when using Electron. 

Would you accept a pull request that provides an option to switch to hash-based routing which would then use setRoute instead of pushState?

**Comment by RainerAtSpirit** [comment]
https://github.com/kitze/mobx-router/issues/7

**Comment by thdk** [comment]
Done in #98
