### ISSUE TITLE
Is it possible to have autoruns subscribing to router properties?

### ISSUE THREAD

**Issue by sadasant** [kitze/mobx-router#35]
Currently, the object we get from `new RouterStore` has observable objects that can't be observed by themselves. For example, something like the following doesn't seem to trigger if the currentPath or the params change:

```
let router = RouterStore()
// creating the routes and calling startRouter
autorun(() =>{
  console.log(router.params)
  console.log(router.currentPath)
})
```

The sites where we've been using this project work properly, but this is something we would like to have. Are we missing something?

Thank you all for the effort put into this project 👍

**Comment by thdk** [comment]
Probably to late, but yes, it should be. I also noticed these weren't observable this week. I think it's an easy fix and will look into it.

**Comment by thdk** [comment]
Actually I just tried it again and it seems to work as expected. I'll reopen this issue if the case would reappear.
