### ISSUE TITLE
React warns deprecated

### ISSUE THREAD

**Issue by kaladivo** [kitze/mobx-router#36]
When using mobx-rotuer, React library gives me those warrnings: 

```
lowPriorityWarning.js:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

```
lowPriorityWarning.js:40 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

Is there any way how to solve them? It seems like mobx-router is using react the outdated way...

**Comment by gordongordon** [comment]
No,  I don't have this problem! With this Package.son
`{
  "name": "mobx-react-ant-boilerplate",
  "version": "1.0.1",
  "description": "MobX Boilerplate with Ant.Design",
  "scripts": {
    "start": "node server.js",
    "lint": "eslint src"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/yonibot/mobx-react-ant-boilerplate"
  },
  "keywords": [
    "react",
    "reactjs",
    "boilerplate",
    "mobx",
    "starter-kit"
  ],
  "author": "Yoni Weisbrod <yoni@fastmail.com> (http://github.com/yonibot)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/mobxjs/mobx/issues"
  },
  "homepage": "http://mobxjs.github.com/mobx",
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.4.1",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-1": "^6.22.0",
    "babel-plugin-import": "^1.2.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "eslint": "^2.13.1",
    "eslint-plugin-react": "^5.1.1",
    "less": "^2.7.2",
    "less-loader": "^4.0.4",
    "node-sass": "^4.3.0",
    "react-hot-loader": "^1.3.1",
    "sass-loader": "^4.1.1",
    "svg-sprite-loader": "^0.3.1",
    "postcss-loader": "^2.0.6",
    "css-loader": "^0.26.1",
    "style-loader": "^0.13.1",
    "postcss-pxtorem": "^4.0.1",
    "webpack-dev-server": "^1.16.5"
  },
  "dependencies": {
    "antd": "^2.5.3",
    "antd-mobile": "^1.4.2",
    "antd-mobile-demo-data": "^0.1.4",
    "firebase": "^4.1.3",
    "history": "^4.6.3",
    "mobx": "^3.1.16",
    "mobx-react": "^4.2.2",
    "mobx-react-devtools": "^4.2.15",
    "mobx-react-form": "^1.31.14",
    "mobx-router": "0.0.7",
    "moment": "^2.18.1",
    "node-uuid": "^1.4.8",
    "path-to-regexp": "^1.7.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-fastclick": "^3.0.2",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "validatorjs": "^3.13.3",
    "webpack": "^1.15.0"
  }
}
`

**Comment by mattscooter** [comment]
I am also seeing the same warnings.  Note that the warnings were introduced in react v15.5, which is why gordongordon isn't seeing the same error, since he is using 15.4.2.

I've checked the code and it appears that there is no reference to createClass or React.PropTypes in the actual code of the mobx-router so I think it must be introduced by one of the node dependencies or the babel build process.

**Comment by VsevolodTrofimov** [comment]
I've taken a look at the dist (compiled) code.
No signs of react's create Class.

No idea where the warning comes from.

**Comment by thdk** [comment]
mobx-router requires a minimum version of React 16.8.*
