### ISSUE TITLE
Why doesn't goTo() sometimes trigger my view rendering?

### ISSUE THREAD

**Issue by peterbe** [kitze/mobx-router#4]
I don't know if this is a bug in mobx-router or my misunderstand or a bug in my prototype. 

My code looks something like this:

``` jsx
// This is component Home

  startSearch(q) {
    // this.props.store.app.setSearch(q)
    console.log("Doing a goTo with", q);
    this.props.store.router.goTo(views.search, {q: q}, this.props.store)
  }

  onSubmit(event) {
    event.preventDefault()
    let q = this.refs.q.value.trim()
    this.startSearch(q)
  }
  render() {
    ...
    <form action="" onSubmit={onSubmit}>
     <input type="search" ref="q" placeholder="Something something..." />
    </form>
    ...
  }
```

And the route config looks like this:

``` javascript
const views = {
  home: new Route({
    path: '/',
    component: <Home/>,
    onEnter: (route, params, store) => {
      console.log('Entering Home');
      store.app.results = null
      store.app.search = null
    }
  }),
  // Note that the views.search view shares the same component as views.home
  search: new Route({
    path: '/q/:q',
    component: <Home/>,
    onEnter: (route, params, store) => {
      console.log("ENTERING Search", params.q);
      // Use params.q to trigger a remote fetch of search results
    }
  }),
  ...
```

So when I'm on the route `/` and trigger that `onSubmit` which triggers the `router.goTo(views.search, ...)` it works. The `onEnter` for view `search` does run. 

However, when I'm already on the view `search` and trigger the same `onSubmit` and `router.goTo(views.search, {different: parametersthistime}, ...)` then it does NOT render the view. I.e. that little `console.log("ENTERING Search", params.q);` does NOT happen. The URL in the address bar changes but no new `onEnter`. 

Is this because the view _name_ is unchanged?

**Comment by peterbe** [comment]
Aha! [Here it is](https://github.com/kitze/mobx-router/blob/d5c88981db66f0c6c67cbcc0cc5327d6f4101dbd/src/router-store.js#L14)

Because the view hasn't changed, it refused to proceed. I.e. it exits early on `rootViewChanged && view.onEnter && view.onEnter(view, this.params, store);` on calling the `view.onEnter(...)`.

It needs to decide if the view has changed based on the parameters too. 

If you're on `/documents/1111` and from there click a link to go to `/documents/2222` you'll want to re-render that document view as a new view rendering. 

How about something like:

```
const rootViewChanged = !this.currentView || (this.currentView.rootPath !== view.rootPath) || (
    !_.isEqual(this.params, mobx.toJS(paramsObj))
);
```
It's important to use `mobx.toJS` when comparing because of its escaping. 

Shall I make a PR?

**Comment by kitze** [comment]
@peterbe You're right, the onEnter event intentionally doesn't trigger on parameters change. I'm planning to introduce another hook called "onParamsChange" for this. onEnter and onExit functions should trigger only when the root path changes. You can try your hand at doing a PR for "onParamsChange" if you want.

**Comment by peterbe** [comment]
Interesting. So if someone goes from `/` to `/documents/123` it will trigger the `onEnter`. And if someone goes from `/documents/456` it will trigger `onParamsChange`. 
But will going from `/` to `/documents/123` *also* trigger an `onParamsChange`?

They feel like 3 different URLs. And I guess I'd have to do something like this:

```jsx
  search: new Route({
    path: '/q/:q',
    component: <Home/>,
    onEnter: (route, params, store) => {
      executeSearchAndUpdateStore(params.q, store)
    },
    onParamsChange: (route, params, store) => {
      executeSearchAndUpdateStore(params.q, store)
    }
  }),
```

I'm not convinced that `/documents/123` is any more similar to `/documents/456` than it is to `/about.html` or `/` or `/other/page`.

What does feel more natural is to re-use the same route when the URL is the same but the query string is different. E.g. Calling `/documents/123` and `/documents/123?expand=info` should perhaps NOT trigger the `onEnter` but should trigger something like a `onQueryStringChange`. (Perhaps a bad argument because query strings are best picked up other ways).

**Comment by kitze** [comment]
If *anything* after the root route ```/documents``` changes, onParamsChange will trigger, should be pretty simple.

**Comment by peterbe** [comment]
Ah. Cool. That means I'll not be using the `onEnter`. But always the `onParamsChange`. 
Which is kinda odd sounding maybe. 
If I've gone from `/` to `/documents` it makes sense to use the `onEnter` but to go from `/` to `/documents/123` I have to use `onParamsChange`. 

But it'll work. Perhaps it's useful to have both. E.g. 

```jsx
  search: new Route({
    path: '/documents/:id',
    component: <Documents/>,
    onEnter: (route, params, store) => {
      console.log('Entering one of the documents for the first time');
    },
    onParamsChange: (route, params, store) => {
      fetchDocumentAndUpdateStore(params.id, store)
    }
  }),
```

Looking forward to it!

**Comment by peterbe** [comment]
I can help you by "reproducing" it in the example app. Then we can use that to test the new onParamsChange feature.

**Comment by kitze** [comment]
No actually if you go from '/' to '/documents/123' you would use onEnter. If you go from '/documents/123/' to '/documents/456' you would use onParamsChange.

You can setup the sample repo, and I'll implement this soon.

**Comment by peterbe** [comment]
> No actually if you go from '/' to '/documents/123' you would use onEnter. If you go from '/documents/123/' to '/documents/456' you would use onParamsChange.

Two me that's a bit annoying. I'd have to implement some common function that either gets called from `onEnter` or from `onParamsChange`. To me, they're 3 different distinct URLs. But I can certainly think of nice optimizations when I can reuse stuff that both `/documents/123` and `/documents/456` need to share. 

> You can setup the sample repo, and I'll implement this soon.

Yes I'll try to do that.

**Comment by tanzim** [comment]
To me, /document/1 -> /document/2 is a path change and should result in an `onEnter`. /document/1?type=foo&value=bar -> /document/1?type=foo1&value=bar should be a params change (or query change). Same top level route data, but potentially different sub-route data. Using this philosophy, it's easy to isolate when to use `onEnter` vs when to use `onParamsUpdate`. I think that's what @peterbe was insinuating?

**Comment by congrady** [comment]
Is anyone working on that onParamsChange hook? I like separating main route navigation hook from it's params hook, but I need to do stuff even when params change. For example fetch another user data when going from #user/1 to #user/2.

I like mobx router a lot, and I'd like to get rid of react router, but this inability to do stuff when params change is crucial for my use case.

**Comment by kitze** [comment]
Ah I know, I need it too. It will be implemented until the end of this week.

**Comment by kitze** [comment]
@congrady @peterbe just implemented this, let me know if it's fine.

**Comment by peterbe** [comment]
Awesome! Didn't I make a PR on the example app or something that demonstrated this. I'll take a look at that again.

**Comment by kitze** [comment]
@peterbe I also updated the mobx-router-example repo.
