### ISSUE TITLE
falsy (ie `0`) param values are being ignored

### ISSUE THREAD

**Issue by VsevolodTrofimov** [kitze/mobx-router#46]
for example I have a route path `mentor/:id`
So `/mentor/1` works fine
`/mentor/0` (with id=0) is replaced as `/mentor` 

So I suggest changing `newPath = value ? newPath.replace(paramKey, value) : newPath.replace(`/${paramKey}`, '');` with a `null` \ `undifned` check

`route.js`, line 57 as for master branch

I can make a PR, but that might be too much for 1 line

**Comment by kitze** [comment]
@VsevolodTrofimov Can you please make a PR? There is nothing wrong with one line PRs.
