### ISSUE TITLE
Outdated mobx

### ISSUE THREAD

**Issue by VsevolodTrofimov** [kitze/mobx-router#47]
![image](https://user-images.githubusercontent.com/10118898/31045426-1cc2137e-a5ec-11e7-97e1-4021b3194df5.png)

Package json has mobx version specified explicitly, maybe allow newer versions? (i.e. `^2.5.1 insted if '2.5.1').
Because current state results in mobx being included twice.

**Comment by VsevolodTrofimov** [comment]
Same for mobx react actually

**Comment by tomitrescak** [comment]
Is this project receiving any :hear: 
I tried to fork it, update to newest packages such as Mobx, React, but I can no longer build with this error: "Error: 'createElement' is not exported by node_modules/react/index.js"

Would you consider removing mobx / mobs-react  and react and keep it as peer dependency?
Would be also great to see this working with react 16.

**Comment by pabloa** [comment]
It seems this fork solves it: https://github.com/elektronik2k5/mobx-router/commit/36610e7dacee4df593719c69d1bb4a50fdd65ec6
@kitze could you please apply https://github.com/elektronik2k5/mobx-router ?

**Comment by nareshbhatia** [comment]
I have updated to the latest mobx + react on my fork: https://github.com/nareshbhatia/mobx-router. There were a few gotcha's with the update, but all cleaned up now. Please see commit comments for details. I have also made bunch of build improvements, e.g. added Lint and Prettier.

**Comment by kitze** [comment]
Merged @nareshbhatia PR, updated all packages to latest versions.
