### ISSUE TITLE
Is this idiomatic ?

### ISSUE THREAD

**Issue by jbrodriguez** [kitze/mobx-router#6]
I want to redirect an unauthorized user if he's deep linking into a private path without credentials.

This is working, but I'm wondering if it's the best way to do it.

```javascript
const views = {
	home: new Route({ path: '/', component: <Home /> }),
	perms: new Route({
		path: '/private',
		component: <Private />,
		beforeEnter: (route, params, store) => {
			if (!store.app.isAuthorized) {
				store.router.goTo(views.home)
				return false
			}
		}
	})
}
```

**Comment by kitze** [comment]
Yes that is fine. What I want to do is make the hooks like "beforeEnter" accept an array of functions. In this case you can extract the "isAuthorized" function and just plug it into one of the arrays.

**Comment by jbrodriguez** [comment]
ok, got it ... will look for that change, thanks !
