### ISSUE TITLE
Nested routes?

### ISSUE THREAD

**Issue by lucianomilen** [kitze/mobx-router#65]
First of all, thank you for `mobx-router`!
I've been facing an issue with nested routes... My case is I have an `index.js` file, where I set up a router to render `/login` and `/app`. After the user logs in, I redirect him to `/app` route. Pretty simple.

The problem is my app component has a sidebar with menu items in it and renders some content (next to the sidebar). I have a `/posts` item and a `/user` item (and `posts/:id` in the future). My first approach was to build another router to deal with this "internal" routes, but I reckon this isn't the best way to deal with it. I was looking for something more generic like react-router, that provides nested routes. So I would have in one `views.js` file something like this:

```
const views = {
  login: new Route({
    path: "/",
    component: <LoginContainer />
  }),
  app: new Route({
    path: "/app",
    component: <AppContainer />,
    beforeEnter: (route, params, store) => {
      if (!_verifyUserLogged(store.userStore)) {
        store.router.goTo(indexViews.login);
        return false;
      }
    }
  }),
  postList: new Route({
    path: "/app/post-list",
    component: <PostContainer />
  }),
  users: new Route({
    path: "/app/users",
    component: <UsersContainer />
  })
...
```
And render the `app` component, that has a sidebar, alongside with either the `PostContainer` or `UserContainer` depending on user navigation.

Is this possible or do I have to separate the routers?

**Comment by thdk** [comment]
You can create an App component.

```
export class App extends React.Component {
    render() {
        return (
            <>
                <HeaderComponent></HeaderComponent>
                <SideBarComponent>
                    <Menu></Menu>
                </SideBarComponent>

                <div app-content">
                      {this.props.children}
                </div>
            </>
        );
    }
}
```
And then simply wrap your **PostContainer** and "UserContainer" with the **App** in the mobx-router config like below:
```
...
 postList: new Route({
    path: "/app/post-list",
    component: <App><PostContainer /></App>
  }),
  users: new Route({
    path: "/app/users",
    component: <App><UsersContainer /></App>
  })
...
```
```

```

**Comment by lucianomilen** [comment]
@thdk that's an interesting approach, but it feels like the whole `app` component would be re-rendered, since the Route calls for a new `app` every time the route changes. Is this the only way to deal with this issue? It doesn't seem like a good strategy to deal with nested routes.

**Comment by thdk** [comment]
@lucianomilen you are right. It seems the whole app component is indeed rendered again. But for my current application that's not such a big problem as it's very light. I'll dig into this later once I have more knowledge of react and mobx. 

Is it something like React Router's named components you are looking for? https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#named-components
Of course that's without the mobx benefits.

**Comment by lucianomilen** [comment]
@thdk I finally switched to standard [React Router](https://github.com/ReactTraining/react-router) and easily found what I was looking for.
Thank you anyway! I'm closing this issue, although that's a good suggestion to this component.
