### ISSUE TITLE
Adding support for html5history:false

### ISSUE THREAD

**Issue by RainerAtSpirit** [kitze/mobx-router#7]
This should address scenarios like https://github.com/kitze/mobx-router/issues/5 where the underlying server doesn't support deep linking.

Here's a hardcoded mockup that sets it to false and updates autorun.
```javascript
...
const createDirectorRouter = (views, store) => {
  new Router({
    ...viewsForDirector(views, store)
  }).configure({
    html5history: false
  }).init('/');
};

const startRouter = (views, store) => {
  //create director configuration
  createDirectorRouter(views, store);

  //autorun and watch for path changes
  autorun(() => {
    const {currentPath} = store.router;
    const hash = `#${path}`;
    if (path !== window.location.hash) {
      window.history.pushState(null, null, hash);
    }
  });
};

export default startRouter;
```

**Comment by kitze** [comment]
Just closed #5 , it was a problem with the hosting of the examples. Deep links should work perfectly fine.

**Comment by RainerAtSpirit** [comment]
I'm aware of the fact that #5 was an issue with the server :). It would be still great having the option to use hash-history. Shouldn't be too hard to implement by allowing a third  optional `{html5history: true|false (default)}` argument.

**Comment by RainerAtSpirit** [comment]
Forgot to add I can send a PR for that if you think that supporting hash-history is a useful capability for mobx-router.

**Comment by TimDaub** [comment]
Has this been considered? I'd like to host on github pages and the only way I see paths like e.g. `/a/b/0` working is with hash-history.

I can submit a PR if necessary.

**Comment by TimDaub** [comment]
I added this via: #73
