### ISSUE TITLE
How to render 404 error page?

### ISSUE THREAD

**Issue by ddinggu** [kitze/mobx-router#77]
Hi.

I want to render 404 error page when not matched routers like [react-router-dom example](https://reacttraining.com/react-router/web/example/no-match).

I can't find any idea in this mobx-router-example or other projects.

Please help this problem. 
Thank you.

**Comment by fastwit** [comment]
Similarly to example you have provided, you can place a catch-all route at the end of your routes config,
```jsx
const views = {
  home: new Route({path: '/', component: <Home />}),
  // ... all valid routes should be listed here 
  catchAll: new Route({path: '/:unknown_url', component: <ErrorPage />})
};
```
also, you can use onEnter to handle additional logic for exceptional cases.

**Comment by ddinggu** [comment]
Thanks to Reply!
