### ISSUE TITLE
store in undefined when I use .goTo

### ISSUE THREAD

**Issue by ekokotov** [kitze/mobx-router#80]
![image](https://user-images.githubusercontent.com/11966000/64364418-7f4da480-d01b-11e9-9be2-ddf0be49376b.png)

**Comment by ekokotov** [comment]
When I reload the page with this route, everything is ok. but when I redirect using `.goTo` store in always undefined

**Comment by ekokotov** [comment]
Seems like I had to pass store in `.goTo` ;(.
I had to extend your router and  pass my `root store` to `.goTo`

**Comment by thdk** [comment]
@ekokotov When your Route doesn't use the `store`argument in any of it's lifecycle methods, you don't need to pass `store` to `goTo`. However, as soon as one of your lifecycle methods (onEnter, onExit, beforeEnter,...) use the store argument, then you must always pass the store when calling `goTo`.
