### ISSUE TITLE
Support to Mobx State Tree

### ISSUE THREAD

**Issue by nkint** [kitze/mobx-router#94]
Hi!
Just a curiosity then a real issue.

Has anyone ever thought about integrate this wonderful project with mobx-state-tree?

**Comment by nkint** [comment]
Thanks for answer. In mobx-state-tree there is a more structured way to define state, I will try to set up something, thanks!

**Comment by kitze** [comment]
@nkint check out rttr -> https://github.com/kitze/rttr

**Comment by iswara108** [comment]
@kitze The example doesn't have a mobx-state-tree in it. Is the intention of rttr to have two separate stores? One for routing and the other for the mobx-state-tree while adding two levels to the component hierarchy to provide the two store contexts?

Second question: How would you use routing in [mst-gql](https://github.com/mobxjs/mst-gql)?

**Comment by kitze** [comment]
@iswara108 you can use [rttr](https://github.com/kitze/rttr) for MST apps. I have no idea how to use it with `mst-gql` tho, sorry.
